# Generated by Django 5.2.3 on 2025-07-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apply_until',
            field=models.DateTimeField(blank=True, help_text='Deadline for applications', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='apply_until',
            field=models.DateTimeField(blank=True, help_text='Deadline for team applications', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_currency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='upcoming', max_length=20),
        ),
    ]
