# Generated by Django 5.2.3 on 2025-07-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='events.event'),
        ),
    ]
