# Generated by Django 5.2.3 on 2025-07-12 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='cosmetics/banners/')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Cost in in-game currency')),
                ('is_unlockable', models.BooleanField(default=False, help_text='Can be unlocked via achievements, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='UserBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.profilebanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'banner')},
            },
        ),
    ]
