# Generated by Django 5.2.3 on 2025-07-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('common', 'Common (C)'), ('uncommon', 'Uncommon (U)'), ('rare', 'Rare (R)'), ('epic', 'Epic (E)'), ('legendary', 'Legendary (L)'), ('mythic', 'Mythic (M)'), ('relic', 'Relic (Re)'), ('masterwork', 'Masterwork (Ma)'), ('eternal', 'Eternal (Et)')], default='common', max_length=20)),
                ('power', models.PositiveIntegerField(default=0, help_text='The power bonus this item provides, if any.')),
                ('tradable', models.BooleanField(default=True)),
                ('limited_edition', models.BooleanField(default=False)),
                ('admin_approval_required', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_icons/')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_per_user', models.PositiveIntegerField(default=99, help_text='Maximum number of this item a user can hold.')),
                ('is_stackable', models.BooleanField(default=True, help_text='Can multiple instances of this item stack in the inventory?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='items', to='items.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='For storing unique item data like enhancements, origin, etc.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_inventories', to='items.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_equipped', True)), fields=('user', 'item'), name='unique_equipped_item')],
            },
        ),
    ]
