# Generated by Django 5.2.3 on 2025-07-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userachievement',
            old_name='awarded_at',
            new_name='unlocked_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='awarded_for',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/icons/'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlock_condition',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userachievement',
            name='displayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
